version: '3.8'

services:
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      context: .
    image: "semantic-search-api:1.0.0"
    ports:
      - "8087:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db